name: Release bundle

on:
  push:
    tags:
      - '*'

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get minor version
      id: get_minor
      run: echo ::set-output name=minor::$(echo ${GITHUB_REF:14}) # refs/tags/2.9.
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Build documentation
      run: |
        pip3 install mkdocs
        mkdocs build
    - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-11
      with:
        args: assembleBundleDist -Pcopy-docs
        env:
          ORG_GRADLE_PROJECT_VERSION_MINOR=${{ steps.outputs.get_minor.minor }}
    - uses: actions/create-release@v1.0.0
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: false
    - uses: actions/upload-release-asset@v1.0.1
      id: upload-release_asset 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ${{ format('./build/distributions/yguard-bundle-2.9.{0}.zip', steps.outputs.get_minor.minor ) }}
        asset_name: ${{ format('yguard-bundle-2.9.{0}.zip', steps.outputs.get_minor.minor ) }}
        asset_content_type: application/zip
